### ISSUE TITLE
About Us Page

### ISSUE THREAD

**Issue by greeenboi** [founder-srm/Camber-monorepo#10]
refer to drive for assets. 

Refer to [ https://camber-racing.netlify.app/aboutus.html](https://camber-racing.netlify.app/aboutus.html) for content

You are to essentially copy it and you are free to add your own twist to it

<sub><a href="https://huly.app/guest/founderstechnical?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmVhY2I0OTQ5YzY4N2Y5NWNmMWRhNzAiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZ3JlZWVuLWZvdW5kZXJzdGVjaC02NmFlNzdiYy01ZmUxN2YzMTYzLTJhNzUzZSJ9.pIvgL0LWChQeqPwVUKyOddu8VXb8AStDagAyJFQaPCg">Huly&reg;: <b>CAMBE-10</b></a></sub>

**Comment by greeenboi** [comment]
@hanish-rishen  Unfortunately in the about page, there seems to be a hydration error. fix the order of the hooks / elements below and send a new pr. also sync up with main branch

![image](https://github.com/user-attachments/assets/7fd5041f-8f94-48be-b62d-e75d42fc6187)

**Comment by hanish-rishen** [comment]
@greeenboi  ok no worries i will fix the hydration error

**Comment by greeenboi** [comment]
#16 fix

**Comment by greeenboi** [comment]
#16 Fixed
