### ISSUE TITLE
Create Partners Page

### ISSUE THREAD

**Issue by greeenboi** [founder-srm/Camber-monorepo#4]
Make it similar to <https://camber-racing.netlify.app/partners.html>

<sub><a href="https://huly.app/guest/founderstechnical?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmVhYzg3YTQ5YzY4N2Y5NWNmMWNkNzQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHViZ3JlZWVuLWZvdW5kZXJzdGVjaC02NmFlNzdiYy01ZmUxN2YzMTYzLTJhNzUzZSJ9.Qvu3mZtec02F4QoVX0OXpXWp_bhI0gHnjFWB-wuWAJ4">Huly&reg;: <b>CAMBE-6</b></a></sub>

**Comment by SaranshBangar** [comment]
[Suvan GS](https://huly.app/browse/?workspace=w-githubgreeen-founderstech-66ae77bc-5fe17f3163-2a753e&_class=contact%3Aclass%3APerson&_id=66ae77cc5fe17f31632a769e&label=Suvan%20GS) <https://github.com/founder-srm/Camber-monorepo/pull/11>
